name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags (v1.6.0, v1.7.0, etc.)
  workflow_dispatch:  # Manual trigger
    inputs:
      version:
        description: 'Version to build (e.g., 1.6.0)'
        required: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target universal-apple-darwin'
          - platform: 'windows-latest'
            args: ''
          - platform: 'ubuntu-22.04'
            args: ''

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libssl-dev

      - name: Install frontend dependencies
        run: npm ci

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Stiftung der DPolG Buchungssystem ${{ github.ref_name }}'
          releaseBody: |
            ## 🎉 Neue Version verfügbar!

            ### Installation
            - **Windows**: Laden Sie die `.msi` oder `.exe` Datei herunter
            - **macOS**: Laden Sie die `.dmg` Datei herunter
            - **Linux**: Laden Sie die `.AppImage` Datei herunter

            ### Automatisches Update
            Wenn Sie bereits eine vorherige Version installiert haben, wird die App automatisch ein Update anbieten.

            ### Änderungen
            Siehe Commit-Historie für Details.
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}

  create-updater-json:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate updater JSON
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${TAG#v}"

          cat > latest.json << INNER_EOF
          {
            "version": "$VERSION",
            "notes": "See release notes for details",
            "pub_date": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "platforms": {
              "darwin-aarch64": {
                "signature": "",
                "url": "https://github.com/${{ github.repository }}/releases/download/$TAG/Stiftung.der.DPolG.Buchungssystem_${VERSION}_aarch64.app.tar.gz"
              },
              "darwin-x86_64": {
                "signature": "",
                "url": "https://github.com/${{ github.repository }}/releases/download/$TAG/Stiftung.der.DPolG.Buchungssystem_${VERSION}_x64.app.tar.gz"
              },
              "linux-x86_64": {
                "signature": "",
                "url": "https://github.com/${{ github.repository }}/releases/download/$TAG/stiftung-der-d-polg-buchungssystem_${VERSION}_amd64.AppImage.tar.gz"
              },
              "windows-x86_64": {
                "signature": "",
                "url": "https://github.com/${{ github.repository }}/releases/download/$TAG/Stiftung.der.DPolG.Buchungssystem_${VERSION}_x64-setup.nsis.zip"
              }
            }
          }
          INNER_EOF

      - name: Upload updater JSON to release
        uses: softprops/action-gh-release@v1
        with:
          files: latest.json
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
